Insert Into COUNTRY_MASTER Values(1,'India');
Insert Into COUNTRY_MASTER Values(2,'Usa');
Insert Into STATE_MASTER Values(1,1,'Andhra Pradesh');
Insert Into STATE_MASTER Values(2,1,'Karnataka');
Insert Into STATE_MASTER Values(3,2,'New Jersy');
insert into STATE_MASTER values(4,2,'Ohio');
Insert Into CITY_MASTER Values(1,'Vizag',1);
Insert Into CITY_MASTER Values(2,'Guntur',1);
Insert Into CITY_MASTER Values(3,'Banglore',2);
Insert Into CITY_MASTER Values(4,'Mysore',2);
Insert Into CITY_MASTER Values(5,'Maywood',3);
Insert Into CITY_MASTER Values(6,'Westwood',3);
Insert Into CITY_MASTER Values(7,'Oakwood',4);
Insert Into CITY_MASTER Values(8,'Cuyahoga County',4);
